language: objective-c
osx_image: xcode9
script:
    - xcodebuild clean build -sdk iphonesimulator -project ./Example/UIViewAnimationExtensions.xcodeproj -scheme UIViewAnimationExtensions CODE_SIGNING_REQUIRED=NO